# Generated by Django 3.1.12 on 2023-07-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
    ]
